/*
Keycloak Admin REST API

This is a REST API reference for the Keycloak Admin REST API.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ClientProfileRepresentation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientProfileRepresentation{}

// ClientProfileRepresentation struct for ClientProfileRepresentation
type ClientProfileRepresentation struct {
	Name        *string                              `json:"name,omitempty"`
	Description *string                              `json:"description,omitempty"`
	Executors   []ClientPolicyExecutorRepresentation `json:"executors,omitempty"`
}

// NewClientProfileRepresentation instantiates a new ClientProfileRepresentation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientProfileRepresentation() *ClientProfileRepresentation {
	this := ClientProfileRepresentation{}
	return &this
}

// NewClientProfileRepresentationWithDefaults instantiates a new ClientProfileRepresentation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientProfileRepresentationWithDefaults() *ClientProfileRepresentation {
	this := ClientProfileRepresentation{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ClientProfileRepresentation) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientProfileRepresentation) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ClientProfileRepresentation) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ClientProfileRepresentation) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ClientProfileRepresentation) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientProfileRepresentation) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ClientProfileRepresentation) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ClientProfileRepresentation) SetDescription(v string) {
	o.Description = &v
}

// GetExecutors returns the Executors field value if set, zero value otherwise.
func (o *ClientProfileRepresentation) GetExecutors() []ClientPolicyExecutorRepresentation {
	if o == nil || IsNil(o.Executors) {
		var ret []ClientPolicyExecutorRepresentation
		return ret
	}
	return o.Executors
}

// GetExecutorsOk returns a tuple with the Executors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientProfileRepresentation) GetExecutorsOk() ([]ClientPolicyExecutorRepresentation, bool) {
	if o == nil || IsNil(o.Executors) {
		return nil, false
	}
	return o.Executors, true
}

// HasExecutors returns a boolean if a field has been set.
func (o *ClientProfileRepresentation) HasExecutors() bool {
	if o != nil && !IsNil(o.Executors) {
		return true
	}

	return false
}

// SetExecutors gets a reference to the given []ClientPolicyExecutorRepresentation and assigns it to the Executors field.
func (o *ClientProfileRepresentation) SetExecutors(v []ClientPolicyExecutorRepresentation) {
	o.Executors = v
}

func (o ClientProfileRepresentation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientProfileRepresentation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Executors) {
		toSerialize["executors"] = o.Executors
	}
	return toSerialize, nil
}

type NullableClientProfileRepresentation struct {
	value *ClientProfileRepresentation
	isSet bool
}

func (v NullableClientProfileRepresentation) Get() *ClientProfileRepresentation {
	return v.value
}

func (v *NullableClientProfileRepresentation) Set(val *ClientProfileRepresentation) {
	v.value = val
	v.isSet = true
}

func (v NullableClientProfileRepresentation) IsSet() bool {
	return v.isSet
}

func (v *NullableClientProfileRepresentation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientProfileRepresentation(val *ClientProfileRepresentation) *NullableClientProfileRepresentation {
	return &NullableClientProfileRepresentation{value: val, isSet: true}
}

func (v NullableClientProfileRepresentation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientProfileRepresentation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
