/*
Keycloak Admin REST API

This is a REST API reference for the Keycloak Admin REST API.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ClientProfilesRepresentation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientProfilesRepresentation{}

// ClientProfilesRepresentation struct for ClientProfilesRepresentation
type ClientProfilesRepresentation struct {
	Profiles       []ClientProfileRepresentation `json:"profiles,omitempty"`
	GlobalProfiles []ClientProfileRepresentation `json:"globalProfiles,omitempty"`
}

// NewClientProfilesRepresentation instantiates a new ClientProfilesRepresentation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientProfilesRepresentation() *ClientProfilesRepresentation {
	this := ClientProfilesRepresentation{}
	return &this
}

// NewClientProfilesRepresentationWithDefaults instantiates a new ClientProfilesRepresentation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientProfilesRepresentationWithDefaults() *ClientProfilesRepresentation {
	this := ClientProfilesRepresentation{}
	return &this
}

// GetProfiles returns the Profiles field value if set, zero value otherwise.
func (o *ClientProfilesRepresentation) GetProfiles() []ClientProfileRepresentation {
	if o == nil || IsNil(o.Profiles) {
		var ret []ClientProfileRepresentation
		return ret
	}
	return o.Profiles
}

// GetProfilesOk returns a tuple with the Profiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientProfilesRepresentation) GetProfilesOk() ([]ClientProfileRepresentation, bool) {
	if o == nil || IsNil(o.Profiles) {
		return nil, false
	}
	return o.Profiles, true
}

// HasProfiles returns a boolean if a field has been set.
func (o *ClientProfilesRepresentation) HasProfiles() bool {
	if o != nil && !IsNil(o.Profiles) {
		return true
	}

	return false
}

// SetProfiles gets a reference to the given []ClientProfileRepresentation and assigns it to the Profiles field.
func (o *ClientProfilesRepresentation) SetProfiles(v []ClientProfileRepresentation) {
	o.Profiles = v
}

// GetGlobalProfiles returns the GlobalProfiles field value if set, zero value otherwise.
func (o *ClientProfilesRepresentation) GetGlobalProfiles() []ClientProfileRepresentation {
	if o == nil || IsNil(o.GlobalProfiles) {
		var ret []ClientProfileRepresentation
		return ret
	}
	return o.GlobalProfiles
}

// GetGlobalProfilesOk returns a tuple with the GlobalProfiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientProfilesRepresentation) GetGlobalProfilesOk() ([]ClientProfileRepresentation, bool) {
	if o == nil || IsNil(o.GlobalProfiles) {
		return nil, false
	}
	return o.GlobalProfiles, true
}

// HasGlobalProfiles returns a boolean if a field has been set.
func (o *ClientProfilesRepresentation) HasGlobalProfiles() bool {
	if o != nil && !IsNil(o.GlobalProfiles) {
		return true
	}

	return false
}

// SetGlobalProfiles gets a reference to the given []ClientProfileRepresentation and assigns it to the GlobalProfiles field.
func (o *ClientProfilesRepresentation) SetGlobalProfiles(v []ClientProfileRepresentation) {
	o.GlobalProfiles = v
}

func (o ClientProfilesRepresentation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientProfilesRepresentation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Profiles) {
		toSerialize["profiles"] = o.Profiles
	}
	if !IsNil(o.GlobalProfiles) {
		toSerialize["globalProfiles"] = o.GlobalProfiles
	}
	return toSerialize, nil
}

type NullableClientProfilesRepresentation struct {
	value *ClientProfilesRepresentation
	isSet bool
}

func (v NullableClientProfilesRepresentation) Get() *ClientProfilesRepresentation {
	return v.value
}

func (v *NullableClientProfilesRepresentation) Set(val *ClientProfilesRepresentation) {
	v.value = val
	v.isSet = true
}

func (v NullableClientProfilesRepresentation) IsSet() bool {
	return v.isSet
}

func (v *NullableClientProfilesRepresentation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientProfilesRepresentation(val *ClientProfilesRepresentation) *NullableClientProfilesRepresentation {
	return &NullableClientProfilesRepresentation{value: val, isSet: true}
}

func (v NullableClientProfilesRepresentation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientProfilesRepresentation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
